### ISSUE TITLE
Configuration for plug through plug command is ignored

### ISSUE THREAD

**Issue by SeerLite** [alexherbo2/plug.kak#11]
```kak
plug plug https://github.com/alexherbo2/plug.kak %{
	# this configuration will be ignored
}
```
because the `plug` module has already been loaded (or else the `plug` command wouldn't even work).

You could always put the config below `require-module plug`, but that feels kinda wrong...
Putting it in `plug-core` also works, but technically that's just for `autoload`, right? (and I'm guessing at some point plug.kak 2 will even allow not linking `core` at all, right?).

You could make an exception for `plug` itself and hook it to `KakBegin` instead of `ModuleLoaded`, but for that you'd have to introduce a shell call to `plug` :/

What do you think is the right syntax for configuring `plug`?

**Comment by alexherbo2** [comment]
How about a user hook?

- 6ad30e04e2af3e581b838f35b939fcb1c09f444f
- 3df7788ad02c13500f3ffa9985542a2d98ce8c37

**Comment by SeerLite** [comment]
Yeah, that works really great!

Thank you
