### ISSUE TITLE
add alternative configuration for Mac users

### ISSUE THREAD

**Issue by basbebe** [alexherbo2/plug.kak#13]
Due to the way the autoload diractory is symlinked in macOS installs

- https://github.com/mawww/kakoune/issues/1063
- https://github.com/mawww/kakoune/wiki/Running-commands-at-startup

I think the currently recommended way of using this plug.kak will not work.

i guess one would have to 

```sh
git clone https://github.com/alexherbo2/plug.kak ~/.config/kak/plugins/plug.kak
```
and in `kakrc`

```sh
source "%val{config}/plugins/plug.kak/rc/plug.kak"
```

(like *'the other* `plug.kak`')

**Comment by alexherbo2** [comment]
I don’t understand.

plug.kak leverages the use of the autoload.  But you recommend to put the plugins outside of the autoload.

Once the user autoload created, you are in charge of the scripts to load, including the system config.

**Comment by basbebe** [comment]
on macOS, the `~/.config/kak/autoload` directory does not exists.

```sh
echo -debug %val(config)
echo -debug %val(runtime)
```

give

```console
/Users/XYZ/.config/kak
/usr/local/Cellar/kakoune/HEAD-26cf5cd/share/kak
```

If one would create `~/.config/kak/autoload` on a mac, none of the default modules and settings would be available.

https://github.com/mawww/kakoune/issues/1063#issue-197111666
> **NOTE:** If you create this directory, kakoune will stop loading the system directory at `..share/kak/autoload`. You can then simlink the `..share/kak/autoload` directory into your autoload directory or just individual files if you like.
> 
> for example, this would simlink all of the default autoload files into your own autoload directory if you are on a mac:
> 
> ```shell
> ln -s /usr/local/share/kak/autoload ~/.config/kak/autoload/autoload
> ```

So this would only work if 
- mac users also create an additional symlink by hand
- mac users put `plug.kak` in another folder than `autoload`

**Comment by alexherbo2** [comment]
plug.kak creates a copy of the system autoload from `%val{runtime}/autoload` to `%val{config}/autoload/plugins/core`.

**Comment by basbebe** [comment]
why would I question you?

I just tried it out and *of course* it works.
