### ISSUE TITLE
equivalent to load-path?

### ISSUE THREAD

**Issue by basbebe** [alexherbo2/plug.kak#14]
Is there an equivalent to [load-path](https://github.com/robertmeta/plug.kak#loading-plugin-from-different-path)?

**Comment by alexherbo2** [comment]
No, plug.kak has a single source of truth, which is the autoload.

It is intended to be close to what Kakoune does already.

You can however do:

``` kak
plug projects/your-plugin.kak
```

Where the path is relative to your home directory.

**Comment by basbebe** [comment]
This is perfect, thanks!
