### ISSUE TITLE
equivalent to do (e.g. compile after update)

### ISSUE THREAD

**Issue by basbebe** [alexherbo2/plug.kak#15]
Is there a recommended way to accomplish what [do](https://github.com/robertmeta/plug.kak#automatically-do-certain-tasks-on-install-or-update) does?

e.g. [kak-lsp](https://github.com/kak-lsp/kak-lsp/) requires compilation after upgrade.

**Comment by alexherbo2** [comment]
Yep, see [Usage] with kak-lsp.

[Usage]: https://github.com/alexherbo2/plug.kak#usage

**Comment by basbebe** [comment]
although now plugins' settings aren't all in one place anymore, this is a nice solution.

Sorry for missing it and opening this issue.
