### ISSUE TITLE
Pretty output

### ISSUE THREAD

**Issue by alexherbo2** [alexherbo2/plug.kak#5]

**Comment by useredsa** [comment]
If this is about the `*plug*` buffer, I'd recommend to take a look at [kak-ansi](https://github.com/eraserhd/kak-ansi)

**Comment by alexherbo2** [comment]
Yep, it is about the `*plug*` buffer now we got rid of the `terminal` command.  I was thinking to just add a few highlighters and giving better output sentences.

**Comment by alexherbo2** [comment]
@useredsa I added a few highlighters.
