### ISSUE TITLE
Syntax highlighting for plug commands in kakrc?

### ISSUE THREAD

**Issue by SeerLite** [alexherbo2/plug.kak#9]
andreyorst's plug.kak had them and I think they make it easier to read the config.

**Comment by alexherbo2** [comment]
What highlighting exactly?

I think to `plug` and the blocks, but they already highlight as Kakoune commands, as there is no region for them.

**Comment by SeerLite** [comment]
I meant highlighting the commands (`plug`, `plug-old`, `plug-autoload`, etc.) as kakrc keywords.
[Here](https://github.com/robertmeta/plug.kak/blob/cf02b00f3764cbd03ce9ab6eec2f4eed035c0737/rc/plug.kak#L73)'s how it's done in og plug.kak. It doesn't seem too difficult, let me make a quick PR for it
